name: Merge-upstream

on:
  push:
    branches: 
     - master
  schedule:
    - cron: 00 00 * * *
    - cron: 00 12 * * *
    - cron: 00 6 * * *
    - cron: 00 18 * * *

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: dev
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "335908093@qq.com"
        git config --global user.name "railjty"
    - name: Load upstream commits
      run: | 
           git pull https://github.com/Anankke/SSPanel-Uim.git --no-edit --strategy-option ours
           rm -rf .github/workflows/*
           cd .github/workflows/
           apt-get update
           apt-get install wget curl
           wget https://raw.githubusercontent.com/railjty/SSPanel-Uim/dev/.github/workflows/Merge-upstream.yml
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: dev
      run: git push origin $DOWNSTREAM_BRANCH
